# see http://www.appveyor.com/docs/appveyor-yml
# environment info: https://www.appveyor.com/docs/windows-images-software/#visual-studio-2015
image: Visual Studio 2015
#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
 - cmd: msbuild .\src\.build\lessmsi.msbuild /p:TheVersion=%APPVEYOR_BUILD_VERSION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
 assemblies:
  - .\src\.deploy\LessMsi.Tests.dll

artifacts:
- path: 'src\.deploy\chocolateypackage\*.nupkg'
- path: 'src\.deploy\*.zip'

deploy:
  - provider: GitHub # See https://www.appveyor.com/docs/deployment/github/
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'Appveyor deployed v$(APPVEYOR_BUILD_VERSION)'
    auth_token:
      secure: oWfqfhnk8xvX/xrkBmz3jue7DCFM9VzP9MHzvX7T3qBzEIrAuDaue6bKTsVekpNs # encrypted token from https://github.com/settings/tokens
    artifact: /(.*\.nupkg)|(.*\.zip)/ # upload NuGet & zip files to release assets
    draft: false
    prerelease: false
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"

  - provider: NuGet # See https://www.appveyor.com/docs/deployment/nuget/
    # For Chocolatey setup for NuGet see https://blog.gripdev.xyz/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/
    server: https://push.chocolatey.org/
    api_key:
      secure: /Ie5xuB5GTDwElbSN0V+mCyYtYNhfQJRjdoWFUsNsVJW9bq32LNzSlI1cn4OUxIu
    artifact: /.*\.nupkg/
    on:
      branch: master                  # only deploy on master
      appveyor_repo_tag: true         # only deploy when there is a tag pushed
      appveyor_repo_tag_name: publish # only deploy when tag == "publish"